# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Composia_config = debug
  Tests_config = debug
  App_config = debug

else ifeq ($(config),release)
  Composia_config = release
  Tests_config = release
  App_config = release

else ifeq ($(config),dist)
  Composia_config = dist
  Tests_config = dist
  App_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Composia Tests App

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Composia:
ifneq (,$(Composia_config))
	@echo "==== Building Composia ($(Composia_config)) ===="
	@${MAKE} --no-print-directory -C Composia -f Makefile config=$(Composia_config)
endif

Tests:
ifneq (,$(Tests_config))
	@echo "==== Building Tests ($(Tests_config)) ===="
	@${MAKE} --no-print-directory -C Tests -f Makefile config=$(Tests_config)
endif

App:
ifneq (,$(App_config))
	@echo "==== Building App ($(App_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile config=$(App_config)
endif

clean:
	@${MAKE} --no-print-directory -C Composia -f Makefile clean
	@${MAKE} --no-print-directory -C Tests -f Makefile clean
	@${MAKE} --no-print-directory -C App -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Composia"
	@echo "   Tests"
	@echo "   App"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"